trigger: none  # disparo via GitHub Actions

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'

- script: |
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    echo "Simulação de deploy..."
    echo "Você pode colocar aqui um deploy real para Azure Web App, Kubernetes, etc."
  displayName: 'Deploy Simples'
